FROM node:24-alpine

RUN apk add --no-cache python3 make g++

WORKDIR /app

COPY package*.json ./
RUN npm ci --build-from-source

COPY tsconfig*.json ./
COPY src ./src

EXPOSE 5002

CMD ["npm", "run", "dev:watch"]
